import BigNumber from 'bignumber.js';
export declare const BSC_BLOCK_TIME = 2.5;
export declare const ONE_DAY_TIME = 86400000;
export declare const CAKE_PER_BLOCK: BigNumber;
export declare const BLOCKS_PER_YEAR: BigNumber;
export declare const BLOCKS_PER_DAY: BigNumber;
export declare const CAKE_PER_YEAR: BigNumber;
export declare const BASE_URL: string;
export declare const BASE_ADD_LIQUIDITY_URL: string;
export declare const BASE_LIQUIDITY_POOL_URL: string;
export declare const BASE_LIQUIDITY_FARM_URL: string;
export declare const BASE_TRADE_SWAP_URL_OUT: string;
export declare const BASE_TRADE_SWAP_URL_IN: string;
export declare const BASE_VDSG_INVITE_URL: string;
export declare const BASE_NFT_MYSTERY_URL: string;
export declare const BASE_NFT_BAG_URL: string;
export declare const BASE_TOKEN_URL = "https://sv.dsgmetaverse.com/images/tokens/";
export declare const BASE_BSC_SCAN_URL: string;
export declare const LOTTERY_MAX_NUMBER_OF_TICKETS = 50;
export declare const LOTTERY_TICKET_PRICE = 1;
export declare const DEFAULT_TOKEN_DECIMAL: BigNumber;
export declare const DEFAULT_GAS_LIMIT = 2000000;
export declare const DEFAULT_GAS_PRICE = 5;
export declare const AUCTION_BIDDERS_TO_FETCH = 500;
export declare const RECLAIM_AUCTIONS_TO_FETCH = 500;
export declare const AUCTION_WHITELISTED_BIDDERS_TO_FETCH = 500;
export declare const TRADING_FEE_RATE: BigNumber;
export declare const PRICE_USD_PER_POWER: BigNumber;
