import { textShadows } from 'uikit/theme/base';
import { scales, variants } from './types';

export const scaleVariants = {
  [scales.LD]: {
    height: '36px',
    minWidth: '108px',
    padding: '0 24px',
  },
  [scales.MD]: {
    height: '36px',
    padding: '0 24px',
  },
  [scales.SM]: {
    height: '52px',
    width: '202px',
    fontSize: '20px',
    padding: '0 16px',
  },
  [scales.XS]: {
    height: '20px',
    fontSize: '12px',
    padding: '0 8px',
  },
};

export const styleVariants = {
  [variants.LOGIN]: {
    background: `url(/images/commons/btn/enter.png)`,
    backgroundPosition: '0 0',
    width: '210px',
    height: '123px',
    paddingBottom: '48px',
  },
  [variants.PRIMARY]: {
    backgroundColor: '#161920',
    color: 'white',
    border: '2px solid #41B7FF',
    // borderImage: 'url(/images/commons/btn/b3.png) 20 20',
    // borderImage: 'linear-gradient(-29deg, #14F1FD, #1CAAF4) 2 2',
    boxShadow: '0px 0px 9px 0px #41B7FF, inset 0px 0px 9px 0px #41B7FF',
    height: '70px',
    padding: '0 52px',
    borderRadius: '10px',
    overflow: 'hidden',
    textShadow: textShadows.primary,
  },
  [variants.DANGER]: {
    backgroundColor: '#161920',
    color: 'white',
    border: '2px solid #FE4A4A',
    // borderImage: 'url(/images/commons/btn/b3.png) 20 20',
    // borderImage: 'linear-gradient(-29deg, #14F1FD, #1CAAF4) 2 2',
    boxShadow: '0px 0px 9px 0px #FE4A4A, inset 0px 0px 9px 0px #FE4A4A',
    height: '70px',
    padding: '0 52px',
    borderRadius: '10px',
    overflow: 'hidden',
    textShadow: textShadows.tertiary,
  },
  [variants.CUSTOM]: {
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    boxShadow: 'none',
    borderRadius: '0',
  },
  [variants.SECONDARY]: {
    background: 'url(/images/commons/btn/s3.png)',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    height: '74px',
    padding: '0',
    fontSize: '20px',
    width: '212px',
    textShadow: textShadows.secondary,
  },
  [variants.VS]: {
    background: 'url(/images/commons/btn/b1.png)',
    backgroundSize: '100% 100%',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    height: '91px',
    width: '280px',
    padding: '0',
    fontSize: '28px',
    boxShadow: 'none',
  },
  [variants.VS_REFRESH]: {
    background: 'url(/images/commons/btn/s1.png)',
    backgroundSize: '100% 100%',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    height: '105px',
    width: '105px',
    padding: '0',
    boxShadow: 'none',
  },
  [variants.TERTIARY]: {
    background: 'url(/images/commons/btn/s2.png)',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    height: '74px',
    width: '71px',
    padding: '0',
  },
  [variants.TEXT]: {
    backgroundColor: 'transparent',
    color: 'primary',
    boxShadow: 'none',
  },
  [variants.BLACK]: {
    backgroundColor: 'transparent',
    color: 'white',
    border: '20px solid ',
    borderImage: 'url(/images/commons/btn/b4.png) 20 20',
    height: '70px',
    padding: '0px',
    minWidth: '210px',
    borderRadius: '20px',
    overflow: 'hidden',
  },
  [variants.STOP]: {
    background: 'url(/images/commons/btn/b2.png)',
    backgroundSize: '100% 100%',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    height: '100px',
    width: '300px',
    padding: '0',
    fontSize: '28px',
    boxShadow: 'none',
  },
  [variants.TRANSPARENT]: {
    backgroundColor: 'transparent',
    color: 'white',
    border: '4px solid #41B7FF',
    boxShadow: '0px 0px 9px 0px #41B7FF, inset 0px 0px 9px 0px #41B7FF',
    height: '70px',
    padding: '0 52px',
    borderRadius: '20px',
    overflow: 'hidden',
    textShadow: textShadows.primary,
  },
};
