import { textShadows } from 'uikit/theme/base';
import { scales, variants } from './types';

export const scaleVariants = {
  [scales.LD]: {
    height: '36px',
    minWidth: '108px',
    padding: '0 24px',
  },
  [scales.MD]: {
    height: '36px',
    padding: '0 24px',
  },
  [scales.SM]: {
    height: '52px',
    width: '202px',
    fontSize: '20px',
    padding: '0 16px',
  },
  [scales.XS]: {
    height: '20px',
    fontSize: '12px',
    padding: '0 8px',
  },
};

export const styleVariants = {
  [variants.LOGIN]: {
    background: `url(/images/commons/btn/enter.png)`,
    backgroundPosition: '0 0',
    width: '210px',
    height: '123px',
    paddingBottom: '48px',
    color: 'black',
  },
  [variants.PRIMARY]: {
    backgroundColor: '#161920',
    color: 'white',
    border: '2px solid #41B7FF',
    // borderImage: 'url(/images/commons/btn/b3.png) 20 20',
    // borderImage: 'linear-gradient(-29deg, #14F1FD, #1CAAF4) 2 2',
    boxShadow: '0px 0px 9px 0px #41B7FF, inset 0px 0px 9px 0px #41B7FF',
    height: '70px',
    padding: '0 52px',
    borderRadius: '10px',
    overflow: 'hidden',
    textShadow: textShadows.primary,
  },
  [variants.DANGER]: {
    backgroundColor: '#161920',
    color: 'white',
    border: '2px solid #FE4A4A',
    // borderImage: 'url(/images/commons/btn/b3.png) 20 20',
    // borderImage: 'linear-gradient(-29deg, #14F1FD, #1CAAF4) 2 2',
    boxShadow: '0px 0px 9px 0px #FE4A4A, inset 0px 0px 9px 0px #FE4A4A',
    height: '70px',
    padding: '0 52px',
    borderRadius: '10px',
    overflow: 'hidden',
    textShadow: textShadows.tertiary,
  },
  [variants.CUSTOM]: {
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    boxShadow: 'none',
    borderRadius: '0',
  },
  [variants.SECONDARY]: {
    background: 'url(/images/commons/btn/s3.png)',
    backgroundSize: '100% 100%',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    height: '74px',
    padding: '0',
    fontSize: '20px',
    width: '152px',
    textShadow: textShadows.secondary,
  },
  [variants.S2_LONG]: {
    background: 'url(/images/commons/btn/s2-long.png)',
    backgroundColor: 'transparent',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    borderRadius: '0',
    color: 'white',
    border: 'none',
    height: '52px',
    padding: '0',
    fontSize: '16px',
    width: '152px',
    textShadow: textShadows.secondary,
  },
  [variants.VS]: {
    background: 'url(/images/commons/btn/b1.png)',
    backgroundSize: '100% 100%',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    height: '91px',
    width: '280px',
    padding: '0',
    fontSize: '28px',
    boxShadow: 'none',
  },
  [variants.VS_REFRESH]: {
    background: 'url(/images/commons/btn/s1.png)',
    backgroundSize: '100% 100%',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    height: '105px',
    width: '105px',
    padding: '0',
    boxShadow: 'none',
  },
  [variants.TERTIARY]: {
    background: 'url(/images/commons/btn/s2.png)',
    backgroundSize: '100% 100%',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    height: '52px',
    borderRadius: '0',
    width: '50px',
    padding: '0',
  },
  [variants.TEXT]: {
    backgroundColor: 'transparent',
    color: 'primary',
    boxShadow: 'none',
  },
  [variants.BLACK]: {
    // background: 'linear-gradient(180deg, red, blue)',
    background: 'linear-gradient(180deg, #1a1e27, #171b22)',
    color: 'white',
    border: '20px solid ',
    borderImage: 'url(/images/commons/btn/b4.png) 20 20',
    height: '70px',
    padding: '0px',
    minWidth: '180px',
    borderRadius: '20px',
    overflow: 'hidden',
  },
  [variants.STOP]: {
    background: 'url(/images/commons/btn/b2.png)',
    backgroundSize: '100% 100%',
    backgroundColor: 'transparent',
    color: 'white',
    border: 'none',
    height: '100px',
    width: '300px',
    padding: '0',
    fontSize: '28px',
    boxShadow: 'none',
  },
  [variants.PURPLE]: {
    width: '100%',
    height: '57px',
    background: 'linear-gradient(0deg, #1C273D, #25BABE)',
    border: '1px solid',
    borderImage: 'linear-gradient(-29deg, #14F1FD, #1CAAF4) 1 1',
    boxShadow: 'inset 0px 0px 43px 0px #512D58',
    borderRadius: 0,
    fontSize: '24px',
    '-webkit-text-stroke': '1px #030000',
    textStroke: '1px #030000',
    color: '#25BABE',
    overflow: 'hidden',
    padding: 0,
    fontWeight: 'bold',
    // clipPath: `polygon(
    //   0 0,
    //   100% 0,
    //   100% 100%,
    //   0 100%
    // )`,
  },
  [variants.TRANSPARENT]: {
    backgroundColor: 'transparent',
    color: 'white',
    border: '4px solid #41B7FF',
    boxShadow: '0px 0px 9px 0px #41B7FF, inset 0px 0px 9px 0px #41B7FF',
    height: '70px',
    padding: '0 52px',
    borderRadius: '20px',
    overflow: 'hidden',
    textShadow: textShadows.primary,
  },
};
