import React from 'react';
import { TagProps } from 'pancake-uikit';
declare const CoreTag: React.FC<TagProps>;
declare const CommunityTag: React.FC<TagProps>;
declare const DualTag: React.FC<TagProps>;
declare const ManualPoolTag: React.FC<TagProps>;
declare const CompoundingPoolTag: React.FC<TagProps>;
declare const VoteNowTag: React.FC<TagProps>;
declare const SoonTag: React.FC<TagProps>;
declare const ClosedTag: React.FC<TagProps>;
export { CoreTag, CommunityTag, DualTag, ManualPoolTag, CompoundingPoolTag, VoteNowTag, SoonTag, ClosedTag };
