import { RaceType } from 'uikit/theme/types';

export const raceData = {
  [RaceType.PROTOSS]: {
    name: 'race-1',
    desc: 'Spacemen are the mysterious advanced creatures of galaxies. They have the supreme racial civilization, and their highly advanced technology and spiritual abilities give them absolute strength in space. Spacemen have AOE damage skills, and their comprehensive combat power is more balanced than the other two groups.',
    features: 'shield, recovery, AOE',
    children: [
      {
        id: 1,
        name: 'Shuttler',
        desc: 'With three weapons and agility, they can climb over obstacles and pierce attack 3 targets (100%, 50%, 30%).',
        thumb1: '/assets/modal/1/1-1.png',
        thumb2: '/assets/modal/1/1-2.png',
      },
      {
        id: 2,
        name: 'Guard Nolin',
        desc: 'Guard Nolin is the sentinel of the Spacemen group who can pierce attack two targets. ',
        thumb1: '/assets/modal/1/2-1.png',
        thumb2: '/assets/modal/1/2-2.png',
      },
      {
        id: 3,
        name: 'Lightsaber Warrior',
        desc: 'They move very fast, with purify capability.',
        thumb1: '/assets/modal/1/3-1.png',
        thumb2: '/assets/modal/1/3-2.png',
      },
      {
        id: 4,
        name: 'Dark Walker',
        desc: 'With the talent of camouflage, they can avoid most attacks on the battlefield. Their MISS value is extremely high.',
        thumb1: '/assets/modal/1/4-1.png',
        thumb2: '/assets/modal/1/4-2.png',
      },
      {
        id: 5,
        name: 'Shuttler II',
        desc: 'Same as Shuttler I, they can also pierce attack 3 targets (100%, 50%, 30%).',
        thumb1: '/assets/modal/1/5-1.png',
        thumb2: '/assets/modal/1/5-2.png',
      },
      {
        id: 6,
        name: 'Bane',
        desc: 'The most loyal warrior in the Spacemen group, their mechanical gun emits frozen eggs, which can freeze one enemy unit.',
        thumb1: '/assets/modal/1/6-1.png',
        thumb2: '/assets/modal/1/6-2.png',
      },
      {
        id: 7,
        name: 'Destroyer',
        desc: 'With handheld Energy Cannon, they can enable the shield magnetic field for two rounds.',
        thumb1: '/assets/modal/1/7-1.png',
        thumb2: '/assets/modal/1/7-2.png',
      },
      {
        id: 8,
        name: 'Armored Toad',
        desc: 'The lowest-level combat unit of the Spacemen group, but their faith will never change. Meteor hammer is their only attack weapon.',
        thumb1: '/assets/modal/1/8-1.png',
        thumb2: '/assets/modal/1/8-2.png',
      },
      {
        id: 9,
        name: 'Purgatory Bulldog',
        desc: 'Lunatic from purgatory, their skin is thick and has a high ES (9 ES).',
        thumb1: '/assets/modal/1/9-1.png',
        thumb2: '/assets/modal/1/9-2.png',
      },
      {
        id: 10,
        name: 'Aoun',
        desc: 'They are also a high-defence fighter of the Spacemen; they can advance the front-line defence for the troops.',
        thumb1: '/assets/modal/1/10-1.png',
        thumb2: '/assets/modal/1/10-2.png',
      },
      {
        id: 11,
        name: 'Wilderness Dragon',
        desc: 'Aerial combat unit, and low -level combat units',
        thumb1: '/assets/modal/1/11-1.png',
        thumb2: '/assets/modal/1/11-2.png',
      },
      {
        id: 12,
        name: 'Death Rock Dragon',
        desc: 'Aerial combat unit with super long-range attack capability',
        thumb1: '/assets/modal/1/12-1.png',
        thumb2: '/assets/modal/1/12-2.png',
      },
      {
        id: 13,
        name: 'Sealed Earth Demon',
        desc: 'The giant devil whose energy has been sealed, moves very slowly, they can cause damage to a single-target.',
        thumb1: '/assets/modal/1/13-1.png',
        thumb2: '/assets/modal/1/13-2.png',
      },
      {
        id: 14,
        name: 'Silver Dragon',
        desc: 'An aerial combat unit can deliver a freezing effect with very low DEF.',
        thumb1: '/assets/modal/1/14-1.png',
        thumb2: '/assets/modal/1/14-2.png',
      },
      {
        id: 15,
        name: 'Tidal Fish',
        desc: 'They look silly, but with a highly flexible body, they can attack and repel enemies.',
        thumb1: '/assets/modal/1/15-1.png',
        thumb2: '/assets/modal/1/15-2.png',
      },
      {
        id: 16,
        name: 'War Cancer',
        desc: 'Absolute defense force on the ground, with the hard shell, they are fearless on the battlefield.',
        thumb1: '/assets/modal/1/16-1.png',
        thumb2: '/assets/modal/1/16-2.png',
      },
      {
        id: 17,
        name: 'Hammer Dragon',
        desc: 'Simple-minded but absolutely brutal combat unit. They can attack 3 units in a V shape.',
        thumb1: '/assets/modal/1/17-1.png',
        thumb2: '/assets/modal/1/17-2.png',
      },
      {
        id: 18,
        name: 'Sidetail Samurai',
        desc: "Proficient in swordsmanship, they can quickly cut the enemy, who can only hear the sound but can't see the shadow of the sword, with pierce attack capability (100%, 50%, 30%)",
        thumb1: '/assets/modal/1/18-1.png',
        thumb2: '/assets/modal/1/18-2.png',
      },
      {
        id: 19,
        name: 'Ice Stone Giant',
        desc: 'Move slowly, their attack comes with a freezing effect',
        thumb1: '/assets/modal/1/19-1.png',
        thumb2: '/assets/modal/1/19-2.png',
      },
      {
        id: 20,
        name: 'Carrion sucker',
        desc: 'With mutant arms storing high damaged missiles, they can launch a missile attack to blast 4 squares surrounding them.',
        thumb1: '/assets/modal/1/20-1.png',
        thumb2: '/assets/modal/1/20-2.png',
      },
      {
        id: 21,
        name: 'Walking Carrion',
        desc: 'The walking dead in the dark. Close attack, with ES last for 2 rounds.',
        thumb1: '/assets/modal/1/21-1.png',
        thumb2: '/assets/modal/1/21-2.png',
      },
      {
        id: 22,
        name: 'Purgatory executioner',
        desc: 'Lord from purgatory, its red body, represents the blood of all enemies. With X-type 5 points attack. ',
        thumb1: '/assets/modal/1/22-1.png',
        thumb2: '/assets/modal/1/22-2.png',
      },
      {
        id: 23,
        name: 'Short-tailed dragon',
        desc: 'The only short-distance flight unit of the Spacemen with regular attacks.',
        thumb1: '/assets/modal/1/23-1.png',
        thumb2: '/assets/modal/1/23-2.png',
      },
      {
        id: 24,
        name: 'Space Juggernaut',
        desc: "The highest weight unit of the Spacemen, it can control the mind and limit the enemy's thinking. They can repel the unit behind the main unit and have immunity to various types of effects.",
        thumb1: '/assets/modal/1/24-1.png',
        thumb2: '/assets/modal/1/24-2.png',
      },
      {
        id: 25,
        name: 'Spiked Gorilla',
        desc: 'The spikes on their body are not weapons, but their nuclear explosion energy on the chest can deliver immeasurable damage.',
        thumb1: '/assets/modal/1/25-1.png',
        thumb2: '/assets/modal/1/25-2.png',
      },
      {
        id: 26,
        name: 'Ice-crystal Dragon ',
        desc: 'The most flexible combat unit in the air, they can deliver frost effect on the enemy.',
        thumb1: '/assets/modal/1/26-1.png',
        thumb2: '/assets/modal/1/26-2.png',
      },
      {
        id: 27,
        name: 'Ghost Guard',
        desc: 'Small but extremely brutal, with purify capability.',
        thumb1: '/assets/modal/1/27-1.png',
        thumb2: '/assets/modal/1/27-2.png',
      },
      {
        id: 28,
        name: 'Abyss-swallow dragon',
        desc: 'Like other ancient dragons, they can bring devastating abnormal weather, and can freeze one enemy unit.',
        thumb1: '/assets/modal/1/28-1.png',
        thumb2: '/assets/modal/1/28-2.png',
      },
      {
        id: 29,
        name: 'Pyro Dragon',
        desc: 'There is flame energy from space energy in their body, and they can shoot massive fire and burn the enemy to ashes. They can launch a missile attack to blast 4 squares surrounding them.',
        thumb1: '/assets/modal/1/29-1.png',
        thumb2: '/assets/modal/1/29-2.png',
      },
      {
        id: 30,
        name: 'Armor crab',
        desc: 'A close relative of the War Cancer moves slowly, with a conventional attack unit.',
        thumb1: '/assets/modal/1/30-1.png',
        thumb2: '/assets/modal/1/30-2.png',
      },
    ],
  },
  [RaceType.HUMAN]: {
    name: 'race-2',
    desc: 'Interstellar guards composed of the United Legion roam in galaxies. Sophisticated mechanical capabilities and high-tech technology provide absolute combat protection, and they have long-range tactical capabilities, which can give them defense against Zerg. Productivity and building HP are relatively low due to their roam.',
    features: 'defense, healthcare, long-range',
    children: [
      {
        id: 1,
        name: 'Mammoth',
        desc: '1st generation mecha hunter, with high-speed fire bursting ability to pierce attack 3 targets (100%, 50%, 30%).',
        thumb1: '/assets/modal/2/1-1.png',
        thumb2: '/assets/modal/2/1-2.png',
      },
      {
        id: 2,
        name: 'Cannon Tank',
        desc: 'The strongest combat unit of the Terran, with great attack damage capability.',
        thumb1: '/assets/modal/2/2-1.png',
        thumb2: '/assets/modal/2/2-2.png',
      },
      {
        id: 3,
        name: 'Ares',
        desc: 'As a single burst mecha, they can repel the enemy.',
        thumb1: '/assets/modal/2/3-1.png',
        thumb2: '/assets/modal/2/3-2.png',
      },
      {
        id: 4,
        name: 'Riot soldiers',
        desc: 'Shields are always the key to their survival against all kinds of attacks. They can repel enemies, but move slowly.',
        thumb1: '/assets/modal/2/4-1.png',
        thumb2: '/assets/modal/2/4-2.png',
      },
      {
        id: 5,
        name: 'Dragon-Diamond',
        desc: 'The Terran close combat mecha can attack over obstacles.',
        thumb1: '/assets/modal/2/5-1.png',
        thumb2: '/assets/modal/2/5-2.png',
      },
      {
        id: 6,
        name: 'Humanoid Mecha',
        desc: 'The optimized mech launches missile attacks and bombards 4 surrounding areas.',
        thumb1: '/assets/modal/2/6-1.png',
        thumb2: '/assets/modal/2/6-2.png',
      },
      {
        id: 7,
        name: 'Death',
        desc: 'As the 2nd generation mecha hunter with higher damage, they can launch missile attacks and bombards 4 surrounding areas.',
        thumb1: '/assets/modal/2/7-1.png',
        thumb2: '/assets/modal/2/7-2.png',
      },
      {
        id: 8,
        name: 'King Kong',
        desc: 'They have stronger defense and destructive power but move slowly.',
        thumb1: '/assets/modal/2/8-1.png',
        thumb2: '/assets/modal/2/8-2.png',
      },
      {
        id: 9,
        name: 'Berserker Mecha',
        desc: 'Roam through the battlefield with the enabler of special serum, they can easily kill enemies, with high SPR but low ACC.',
        thumb1: '/assets/modal/2/9-1.png',
        thumb2: '/assets/modal/2/9-2.png',
      },
      {
        id: 10,
        name: 'Destroyer',
        desc: 'Weird hexagonal combat machine with single-target attack only.',
        thumb1: '/assets/modal/2/10-1.png',
        thumb2: '/assets/modal/2/10-2.png',
      },
      {
        id: 11,
        name: 'Urgot',
        desc: 'With high-temperature jet flame, they can continually burn the enemy for 4 rounds.',
        thumb1: '/assets/modal/2/11-1.png',
        thumb2: '/assets/modal/2/11-2.png',
      },
      {
        id: 12,
        name: 'Gareth',
        desc: 'Gareth is definitely a game opener, it can attack enemy units for 3 squares.',
        thumb1: '/assets/modal/2/12-1.png',
        thumb2: '/assets/modal/2/12-2.png',
      },
      {
        id: 13,
        name: 'Marauder',
        desc: 'The 3rd generation mecha hunter, they are closer to human form, with extremely high damage and they can launch missile attacks and bombards 4 surrounding areas.',
        thumb1: '/assets/modal/2/13-1.png',
        thumb2: '/assets/modal/2/13-2.png',
      },
      {
        id: '14--1~2',
        name: 'Blue Spider',
        desc: 'Ultra-mobility combat machine, but can only attack one enemy unit.',
        thumb1: '/assets/modal/2/14--1~2-1.png',
        thumb2: '/assets/modal/2/14--1~2-2.png',
      },
      {
        id: '14--3~4',
        name: 'Red Spider',
        desc: 'Ultra-mobility combat machine, they can quickly approach the enemy and cause confusion, but their damage power is extremely low.',
        thumb1: '/assets/modal/2/14--3~4-1.png',
        thumb2: '/assets/modal/2/14--3~4-2.png',
      },
      {
        id: '14--5~6',
        name: 'Copper Spider',
        desc: 'A mechanical unit that can remotely provide HP regeneration for units from its own side.',
        thumb1: '/assets/modal/2/14--5~6-1.png',
        thumb2: '/assets/modal/2/14--5~6-2.png',
      },
      {
        id: '14--7~8',
        name: 'Yellow Spider',
        desc: 'Combat units that can attack 2 squares',
        thumb1: '/assets/modal/2/14--7~8-1.png',
        thumb2: '/assets/modal/2/14--7~8-2.png',
      },
      {
        id: 15,
        name: 'Punisher',
        desc: 'With high-precision tech weapons, violent bombing lasts 4 rounds.',
        thumb1: '/assets/modal/2/15-1.png',
        thumb2: '/assets/modal/2/15-2.png',
      },
      {
        id: 16,
        name: 'Double-headed flame',
        desc: 'Loaded with thermal imaging equipment, they can accurately snipe enemy units.',
        thumb1: '/assets/modal/2/16-1.png',
        thumb2: '/assets/modal/2/16-2.png',
      },
      {
        id: 17,
        name: 'Alpha',
        desc: 'The most mysterious combat unit of Terran, no enemy can survive under their feet. They can approach the enemy and release high-damage bombs for 2 rounds.',
        thumb1: '/assets/modal/2/17-1.png',
        thumb2: '/assets/modal/2/17-2.png',
      },
      {
        id: 18,
        name: 'Humpback Whale',
        desc: 'The Terran aircraft carrier with its energy-collecting cannon, can effectively repel enemies and deal damage.',
        thumb1: '/assets/modal/2/18-1.png',
        thumb2: '/assets/modal/2/18-2.png',
      },
      {
        id: 19,
        name: 'Cheetah',
        desc: 'First strike fighter, can quickly approach the enemy on top to deliver harassment strikes. They also have a purify function.',
        thumb1: '/assets/modal/2/19-1.png',
        thumb2: '/assets/modal/2/19-2.png',
      },
      {
        id: 20,
        name: 'Nightmare',
        desc: 'Medical mission flight unit, which can remotely regenerate one HP for its own side.',
        thumb1: '/assets/modal/2/20-1.png',
        thumb2: '/assets/modal/2/20-2.png',
      },
      {
        id: 21,
        name: 'Crow',
        desc: 'High-mobility fighters in the air with extremely long-range attack capability.',
        thumb1: '/assets/modal/2/21-1.png',
        thumb2: '/assets/modal/2/21-2.png',
      },
      {
        id: 22,
        name: 'Shark',
        desc: 'The escort of human command ships can restore 9 squares on its own side.',
        thumb1: '/assets/modal/2/22-1.png',
        thumb2: '/assets/modal/2/22-2.png',
      },
      {
        id: 23,
        name: 'Zealot MK1',
        desc: "As infrared medic, they can restore 1 HP of one's own units at close range on the battlefield.",
        thumb1: '/assets/modal/2/23-1.png',
        thumb2: '/assets/modal/2/23-2.png',
      },
      {
        id: 24,
        name: 'Zealot MK2',
        desc: 'Infrared semi-automatic mecha warriors are the best choice for the strike force, with high SPR and low ACC.',
        thumb1: '/assets/modal/2/24-1.png',
        thumb2: '/assets/modal/2/24-2.png',
      },
      {
        id: 25,
        name: 'Zealot MK3',
        desc: 'Infrared semi-automatic mecha warriors are the best choice for the strike force.',
        thumb1: '/assets/modal/2/25-1.png',
        thumb2: '/assets/modal/2/25-2.png',
      },
      {
        id: 26,
        name: 'Explorer',
        desc: 'Can easily overcome obstacles and attack enemy units.',
        thumb1: '/assets/modal/2/26-1.png',
        thumb2: '/assets/modal/2/26-2.png',
      },
      {
        id: 27,
        name: 'Victor',
        desc: 'An immobile attack machine, with a very thick HP, very small ATK, but with a repel effect.',
        thumb1: '/assets/modal/2/27-1.png',
        thumb2: '/assets/modal/2/27-2.png',
      },
      {
        id: 28,
        name: 'War Machine',
        desc: 'The oldest troop vanguard of Terran can repel enemy units behind the main attack target.',
        thumb1: '/assets/modal/2/28-1.png',
        thumb2: '/assets/modal/2/28-2.png',
      },
      {
        id: 29,
        name: 'Ranger',
        desc: 'They have a very high MISS value, which is also the foundation of being a ranger, but they have low damage and with single-target repel effect.',
        thumb1: '/assets/modal/2/29-1.png',
        thumb2: '/assets/modal/2/29-2.png',
      },
      {
        id: 30,
        name: 'Tango Wolf',
        desc: 'The energy medicine tube stored at any time can quickly restore 1 HP to your own combat units.',
        thumb1: '/assets/modal/2/30-1.png',
        thumb2: '/assets/modal/2/30-2.png',
      },
    ],
  },
  [RaceType.ZERG]: {
    name: 'race-3',
    desc: 'A brutal race evolved from interstellar creatures, with super high damage power, their innate weapons and armor are comparable to other races, and devoting spirit makes them extremely strong and deadly. But no AOE and short-range attack ability are their weak points.',
    features: 'speed, high burst',
    children: [
      {
        id: 1,
        name: 'Crabworm',
        desc: 'They have a hard shell, and can quickly shuttle through the battlefield.',
        thumb1: '/assets/modal/3/1-1.png',
        thumb2: '/assets/modal/3/1-2.png',
      },
      {
        id: 2,
        name: 'Multi-eyed beast',
        desc: 'With multiple eyes and tentacles, they can quickly detect enemies and conduct sneak attacks, and with repel effect.',
        thumb1: '/assets/modal/3/2-1.png',
        thumb2: '/assets/modal/3/2-2.png',
      },
      {
        id: 3,
        name: 'Self-exploding Worm',
        desc: 'They have a thick shell, very high HP and DEF, and can imprison 1 enemy combat unit.',
        thumb1: '/assets/modal/3/3-1.png',
        thumb2: '/assets/modal/3/3-2.png',
      },
      {
        id: 4,
        name: 'Ground Bull',
        desc: 'They can imprison 1 enemy combat unit.',
        thumb1: '/assets/modal/3/4-1.png',
        thumb2: '/assets/modal/3/4-2.png',
      },
      {
        id: 5,
        name: 'Armored Beetle',
        desc: 'Although they have 4 legs, they cannot move while attacking, and they use the venom in their mouth to attack the enemy.',
        thumb1: '/assets/modal/3/5-1.png',
        thumb2: '/assets/modal/3/5-2.png',
      },
      {
        id: 6,
        name: 'Ant Spider',
        desc: 'Area attack can attack enemy units up to 9 squares',
        thumb1: '/assets/modal/3/6-1.png',
        thumb2: '/assets/modal/3/6-2.png',
      },
      {
        id: 7,
        name: 'Winged Fish',
        desc: 'A fish variant that can fly low in the air, with relatively low ATK.',
        thumb1: '/assets/modal/3/7-1.png',
        thumb2: '/assets/modal/3/7-2.png',
      },
      {
        id: 8,
        name: 'Dragon-feet troll ',
        desc: 'Slow-moving Zerg unit, attack method: conventional attack',
        thumb1: '/assets/modal/3/8-1.png',
        thumb2: '/assets/modal/3/8-2.png',
      },
      {
        id: 9,
        name: 'Abyssal Mouth',
        desc: 'A giant mouth in the shape of a piranha can imprison 1 enemy combat unit.',
        thumb1: '/assets/modal/3/9-1.png',
        thumb2: '/assets/modal/3/9-2.png',
      },
      {
        id: 10,
        name: 'Pincer Beetle',
        desc: 'With two super-heavy pincers, they move slowly, but with repel effect.',
        thumb1: '/assets/modal/3/10-1.png',
        thumb2: '/assets/modal/3/10-2.png',
      },
      {
        id: 11,
        name: 'Spiked Squid',
        desc: 'With the spiky tentacles, they can put enemies into their mouths and attack enemy unit 3 squares away.',
        thumb1: '/assets/modal/3/11-1.png',
        thumb2: '/assets/modal/3/11-2.png',
      },
      {
        id: 12,
        name: 'Nydus Worm',
        desc: 'It can suddenly spring from the tunnel, catch the opponent by surprise, and piercing attack 3 targets',
        thumb1: '/assets/modal/3/12-1.png',
        thumb2: '/assets/modal/3/12-2.png',
      },
      {
        id: 13,
        name: 'Ant Lord',
        desc: "As mutated species from the void, they are enemy's nightmare. They can use venom missiles to bomb 4 targets around.",
        thumb1: '/assets/modal/3/13-1.png',
        thumb2: '/assets/modal/3/13-2.png',
      },
      {
        id: 14,
        name: 'Bison',
        desc: 'The name has nothing to do with its figure. They can regenerate 1 HP with their side at close range.',
        thumb1: '/assets/modal/3/14-1.png',
        thumb2: '/assets/modal/3/14-2.png',
      },
      {
        id: 15,
        name: 'Mammoth Spider',
        desc: "Zerg's giant close combat unit, can imprison 4 surrounding squares.",
        thumb1: '/assets/modal/3/15-1.png',
        thumb2: '/assets/modal/3/15-2.png',
      },
      {
        id: 16,
        name: 'Flying Insect',
        desc: 'Air unit that can imprison enemy units.',
        thumb1: '/assets/modal/3/16-1.png',
        thumb2: '/assets/modal/3/16-2.png',
      },
      {
        id: 17,
        name: 'Stalker',
        desc: 'As close-range combat unit, they can imprison one front and one back enemy unit.',
        thumb1: '/assets/modal/3/17-1.png',
        thumb2: '/assets/modal/3/17-2.png',
      },
      {
        id: 18,
        name: 'Fearless Warrior',
        desc: 'The heroic and invincible Zerg warrior can attack the target one square behind the main attacking unit.',
        thumb1: '/assets/modal/3/18-1.png',
        thumb2: '/assets/modal/3/18-2.png',
      },
      {
        id: 19,
        name: 'Cyclops',
        desc: 'Air Scout with ranged attack capability.',
        thumb1: '/assets/modal/3/19-1.png',
        thumb2: '/assets/modal/3/19-2.png',
      },
      {
        id: 20,
        name: 'Sandworm',
        desc: 'Ground scout, fast moving, rough skin and thick HP.',
        thumb1: '/assets/modal/3/20-1.png',
        thumb2: '/assets/modal/3/20-2.png',
      },
      {
        id: 21,
        name: 'Alien',
        desc: 'Strike unit, can attack 3 enemy units in a V shape.',
        thumb1: '/assets/modal/3/21-1.png',
        thumb2: '/assets/modal/3/21-2.png',
      },
      {
        id: 22,
        name: 'Carrier',
        desc: 'The explosive bomb on their back can be precisely guided for long-range attacks.',
        thumb1: '/assets/modal/3/22-1.png',
        thumb2: '/assets/modal/3/22-2.png',
      },
      {
        id: 23,
        name: 'Blackwater',
        desc: 'A fast-attacking unit on the ground, they can regenerate 1 HP with their side at long range.',
        thumb1: '/assets/modal/3/23-1.png',
        thumb2: '/assets/modal/3/23-2.png',
      },
      {
        id: 24,
        name: 'Quantum Spider',
        desc: 'Made entirely of quantum energy, belongs to tank warriors, they can imprison 1 enemy target',
        thumb1: '/assets/modal/3/24-1.png',
        thumb2: '/assets/modal/3/24-2.png',
      },
      {
        id: 25,
        name: 'Mantis',
        desc: 'They can pull enemy units and hit them, causing damage.',
        thumb1: '/assets/modal/3/25-1.png',
        thumb2: '/assets/modal/3/25-2.png',
      },
      {
        id: 26,
        name: 'Rogue Beast',
        desc: 'With mutant cells, they can rampage in battle, their attack range is 2 squares.',
        thumb1: '/assets/modal/3/26-1.png',
        thumb2: '/assets/modal/3/26-2.png',
      },
      {
        id: 27,
        name: 'Dismembering Shark',
        desc: "Zerg's flesh warriors, move slowly.",
        thumb1: '/assets/modal/3/27-1.png',
        thumb2: '/assets/modal/3/27-2.png',
      },
      {
        id: 28,
        name: 'Crabworm II',
        desc: 'They have a hard shell, and they can quickly shuttle through the battlefield, and imprison enemy unit.',
        thumb1: '/assets/modal/3/28-1.png',
        thumb2: '/assets/modal/3/28-2.png',
      },
      {
        id: 29,
        name: 'Crabworm III',
        desc: 'Immune to imprison effect.',
        thumb1: '/assets/modal/3/29-1.png',
        thumb2: '/assets/modal/3/29-2.png',
      },
      {
        id: 30,
        name: 'Horned Monkey',
        desc: 'With an extremely hard horn, they can deal a lot of damage when approaching enemies, but have low ACC.',
        thumb1: '/assets/modal/3/30-1.png',
        thumb2: '/assets/modal/3/30-2.png',
      },
    ],
  },
};
