import { RaceType } from 'uikit/theme/types';

export const raceData = {
  [RaceType.PROTOSS]: {
    name: 'race-1',
    children: [
      {
        id: 1,
        name: 'Shuttle',
        desc: 'The energy tank on the back stores this space energy, which can be used to quickly travel through space',
        thumb1: '/assets/modal/1/1-1.png',
        thumb2: '/assets/modal/1/1-2.png',
      },
      {
        id: 2,
        name: 'Guard Nolin',
        desc: 'The sentinel of the universe group can quickly send information back to the base, and can also quickly join the battle',
        thumb1: '/assets/modal/1/2-1.png',
        thumb2: '/assets/modal/1/2-2.png',
      },
      {
        id: 3,
        name: 'lightsaber warrior',
        desc: 'The lightsaber is their winning weapon of faith, ignoring most defenses and dealing tons of damage. Including light grenades can also cause extensive damage to places',
        thumb1: '/assets/modal/1/3-1.png',
        thumb2: '/assets/modal/1/3-2.png',
      },
      {
        id: 4,
        name: 'Raider I',
        desc: 'You can disguise yourself to approach the enemy, and quickly switch weapons to cause damage to the enemy',
        thumb1: '/assets/modal/1/4-1.png',
        thumb2: '/assets/modal/1/4-2.png',
      },
      {
        id: 5,
        name: 'Raider II',
        desc: 'Also as raiders, with more objective output ability',
        thumb1: '/assets/modal/1/5-1.png',
        thumb2: '/assets/modal/1/5-2.png',
      },
      {
        id: 6,
        name: 'Bane the Bull',
        desc: 'The most loyal display of the universe group, the ability level is average, but the courage to fight.',
        thumb1: '/assets/modal/1/6-1.png',
        thumb2: '/assets/modal/1/6-2.png',
      },
      {
        id: 7,
        name: 'Destroy',
        desc: 'Holding a cannon energy cannon, it can cause AOE damage to the enemy.',
        thumb1: '/assets/modal/1/7-1.png',
        thumb2: '/assets/modal/1/7-2.png',
      },
      {
        id: 8,
        name: 'Armored Green Toad',
        desc: 'The hard armor on the back can resist damage and is the best choice for the front row. The meteor hammer is the only AOE weapon they attack.',
        thumb1: '/assets/modal/1/8-1.png',
        thumb2: '/assets/modal/1/8-2.png',
      },
      {
        id: 9,
        name: 'Purgatory Bulldog',
        desc: 'A madman from purgatory, as long as he sees the enemy, he will be desperate and knows how to destroy the enemy.',
        thumb1: '/assets/modal/1/9-1.png',
        thumb2: '/assets/modal/1/9-2.png',
      },
      {
        id: 10,
        name: 'Aoun',
        desc: 'It is also a high-defense combat arm of the Cosmic Clan, advancing the wrong front-line defense, one enemy at a time, and showing no mercy.',
        thumb1: '/assets/modal/1/10-1.png',
        thumb2: '/assets/modal/1/10-2.png',
      },
      {
        id: 11,
        name: 'Wilderon',
        desc: 'Aerial combat unit that shoots flames for decent AOE and sustained damage',
        thumb1: '/assets/modal/1/11-1.png',
        thumb2: '/assets/modal/1/11-2.png',
      },
      {
        id: 12,
        name: 'Death Rock Dragon',
        desc: 'Air combat unit that can inflict poisonous damage to places.',
        thumb1: '/assets/modal/1/12-1.png',
        thumb2: '/assets/modal/1/12-2.png',
      },
      {
        id: 13,
        name: 'Seal Earth Demon',
        desc: 'The devouring ability of the strong attack makes it crazy, unable to distinguish between friends and enemies, only the seal can print its ability',
        thumb1: '/assets/modal/1/13-1.png',
        thumb2: '/assets/modal/1/13-2.png',
      },
      {
        id: 14,
        name: 'Fish head silver dragon',
        desc: 'Aerial combat unit that can emit a freezing effect',
        thumb1: '/assets/modal/1/14-1.png',
        thumb2: '/assets/modal/1/14-2.png',
      },
      {
        id: 15,
        name: 'Tidal Fish Monster',
        desc: 'It looks silly, but it has an extremely flexible body that can use weapons to avoid enemy attacks',
        thumb1: '/assets/modal/1/15-1.png',
        thumb2: '/assets/modal/1/15-2.png',
      },
      {
        id: 16,
        name: 'War cancer',
        desc: 'Absolute defense force on the ground, the hard shell can be fearless on the battlefield',
        thumb1: '/assets/modal/1/16-1.png',
        thumb2: '/assets/modal/1/16-2.png',
      },
      {
        id: 17,
        name: 'Demon Hammer Dragon',
        desc: 'Simple-minded, but absolutely brutal combat unit',
        thumb1: '/assets/modal/1/17-1.png',
        thumb2: '/assets/modal/1/17-2.png',
      },
      {
        id: 18,
        name: 'Sidetail Samurai',
        desc: 'Proficient in swordsmanship, can quickly cut the enemy, only hear the sound of the sword but not the shadow of the sword, the most flexible warrior in the universe',
        thumb1: '/assets/modal/1/18-1.png',
        thumb2: '/assets/modal/1/18-2.png',
      },
      {
        id: 19,
        name: 'Stone man',
        desc: 'Although it looks bulky, the jets on the soles of its feet can make it fly into the sky and smash into the ground, causing large-scale damage, but it will also shatter itself.',
        thumb1: '/assets/modal/1/19-1.png',
        thumb2: '/assets/modal/1/19-2.png',
      },
      {
        id: 20,
        name: 'Suck carrion',
        desc: 'The mutated arms have long hooks that suck blood and energy from enemies once hooked',
        thumb1: '/assets/modal/1/20-1.png',
        thumb2: '/assets/modal/1/20-2.png',
      },
      {
        id: 21,
        name: 'Dark Walker Carrion',
        desc: 'The walking dead in the dark',
        thumb1: '/assets/modal/1/21-1.png',
        thumb2: '/assets/modal/1/21-2.png',
      },
      {
        id: 22,
        name: 'Purgatory executioner',
        desc: 'Lord from purgatory, the red body is the blood of all enemies.',
        thumb1: '/assets/modal/1/22-1.png',
        thumb2: '/assets/modal/1/22-2.png',
      },
      {
        id: 23,
        name: 'Short-tailed claw',
        desc: "The only giant dragon that can't fly in the cosmic race, but with its sharp double-edged blades on the ground, it can cause decent damage",
        thumb1: '/assets/modal/1/23-1.png',
        thumb2: '/assets/modal/1/23-2.png',
      },
      {
        id: 24,
        name: 'Space juggernaut',
        desc: 'The highest weight unit of the cosmic family, it has the ability to control the mind and limit the thinking of the enemy.',
        thumb1: '/assets/modal/1/24-1.png',
        thumb2: '/assets/modal/1/24-2.png',
      },
      {
        id: 25,
        name: 'Spiked Giant Gorilla',
        desc: 'The spikes on the body are not weapons, and to contain the ground, the nuclear explosion energy in the chest is the nirvana.',
        thumb1: '/assets/modal/1/25-1.png',
        thumb2: '/assets/modal/1/25-2.png',
      },
      {
        id: 26,
        name: 'Ice Crystal Xunlong',
        desc: 'The most flexible combat unit in the air, can cause frost effect on the enemy',
        thumb1: '/assets/modal/1/26-1.png',
        thumb2: '/assets/modal/1/26-2.png',
      },
      {
        id: 27,
        name: 'Ghost guard',
        desc: 'Small but extremely brutal',
        thumb1: '/assets/modal/1/27-1.png',
        thumb2: '/assets/modal/1/27-2.png',
      },
      {
        id: 28,
        name: 'Swallowing dragon',
        desc: 'Like other ancient dragons, it will bring devastating abnormal weather, tornadoes and sandstorms are the signs of its appearance.',
        thumb1: '/assets/modal/1/28-1.png',
        thumb2: '/assets/modal/1/28-2.png',
      },
      {
        id: 29,
        name: 'Pyro Dragon',
        desc: 'There is flame energy from space energy in the body, and a huge fire burns the place to ashes',
        thumb1: '/assets/modal/1/29-1.png',
        thumb2: '/assets/modal/1/29-2.png',
      },
      {
        id: 30,
        name: 'Armor crab',
        desc: 'A close relative of the war cancer, with camouflage and the ability to quickly approach the enemy',
        thumb1: '/assets/modal/1/30-1.png',
        thumb2: '/assets/modal/1/30-2.png',
      },
    ],
    desc: 'Cosmic beings belong to the mysterious high-level creatures of the galaxy. They have the highest racial civilization, and their highly advanced technology and spiritual abilities give them absolute strength in space. The Cosmos has an AOE damage structure, and its comprehensive combat power is more balanced than the other two groups.',
    features: 'Shield, Restoration, AOE',
  },
  [RaceType.HUMAN]: {
    name: 'race-2',
    children: [
      {
        id: 1,
        name: 'Mammoth',
        desc: 'The 1st generation mecha hunter has a high rate of fire and bursts of thick armor, but the slow action is a disadvantage.',
        thumb1: '/assets/modal/2/1-1.png',
        thumb2: '/assets/modal/2/1-2.png',
      },
      {
        id: 2,
        name: 'Cannon Tank',
        desc: 'The strongest combat unit of the human race, with a decent ranged attack.',
        thumb1: '/assets/modal/2/2-1.png',
        thumb2: '/assets/modal/2/2-2.png',
      },
      {
        id: 3,
        name: 'Mars',
        desc: 'A single burst of mecha can cause tons of damage, but due to energy overload, it will enter a cooling state and cannot continue to attack.',
        thumb1: '/assets/modal/2/3-1.png',
        thumb2: '/assets/modal/2/3-2.png',
      },
      {
        id: 4,
        name: 'Blaster',
        desc: 'The shield will always be the foundation of their existence and can defend against all kinds of attacks.',
        thumb1: '/assets/modal/2/4-1.png',
        thumb2: '/assets/modal/2/4-2.png',
      },
      {
        id: 5,
        name: 'Dragon Drill',
        desc: 'The human melee mech can break through any defense, but a single attack method also makes it easy to become a meat shield.',
        thumb1: '/assets/modal/2/5-1.png',
        thumb2: '/assets/modal/2/5-2.png',
      },
      {
        id: 6,
        name: 'Humanoid Mecha',
        desc: 'The optimized mecha can move quickly and cause continuous damage to the enemy accurately.',
        thumb1: '/assets/modal/2/6-1.png',
        thumb2: '/assets/modal/2/6-2.png',
      },
      {
        id: 7,
        name: 'Grim Reaper',
        desc: '2nd generation mech hunter, high damage and high defense, increased air defense capability, red armor is their belief in victory.',
        thumb1: '/assets/modal/2/7-1.png',
        thumb2: '/assets/modal/2/7-2.png',
      },
      {
        id: 8,
        name: 'King Kong',
        desc: 'It has stronger resistance and destructive power, and can tear the enemy into pieces.',
        thumb1: '/assets/modal/2/8-1.png',
        thumb2: '/assets/modal/2/8-2.png',
      },
      {
        id: 9,
        name: 'Berserker Mecha',
        desc: 'Soldiers traveling through the battlefield, with the blessing of special serum, can easily kill the enemy. But the flesh is always the flesh.',
        thumb1: '/assets/modal/2/9-1.png',
        thumb2: '/assets/modal/2/9-2.png',
      },
      {
        id: 10,
        name: 'Destroy',
        desc: 'Weird hexagonal combat machine, suitable for long-range combat, and flexible layout.',
        thumb1: '/assets/modal/2/10-1.png',
        thumb2: '/assets/modal/2/10-2.png',
      },
      {
        id: 11,
        name: 'Urgot',
        desc: '360° no dead angle attack, can adapt to changes in the battlefield at any time, and the output ability is outstanding.',
        thumb1: '/assets/modal/2/11-1.png',
        thumb2: '/assets/modal/2/11-2.png',
      },
      {
        id: 12,
        name: 'Gareth',
        desc: 'Gareth is definitely a game opener, clearing any obstacles quickly and chasing after victory.',
        thumb1: '/assets/modal/2/12-1.png',
        thumb2: '/assets/modal/2/12-2.png',
      },
      {
        id: 13,
        name: 'Marauder',
        desc: "The 3rd generation mecha hunter is closer to human form, with high mobility and mixed output, turning the enemy's position into ashes.",
        thumb1: '/assets/modal/2/13-1.png',
        thumb2: '/assets/modal/2/13-2.png',
      },
      {
        id: 14,
        name: 'Blue spider',
        desc: 'Ultra-maneuverable combat machine that can quickly approach the enemy and cause confusion for the enemy, but the damage is very low',
        thumb1: '/assets/modal/2/14--1~2-1.png',
        thumb2: '/assets/modal/2/14--1~2-2.png',
      },
      {
        id: 1434,
        name: 'Red spider',
        desc: 'Ultra-maneuverable combat machine that can quickly approach the enemy and cause confusion for the enemy, but the damage is very low',
        thumb1: '/assets/modal/2/14--3~4-1.png',
        thumb2: '/assets/modal/2/14--3~4-2.png',
      },
      {
        id: 1456,
        name: 'Copper spider',
        desc: 'Ultra-maneuverable combat machine that can quickly approach the enemy and cause confusion for the enemy, but the damage is very low',
        thumb1: '/assets/modal/2/14--5~6-1.png',
        thumb2: '/assets/modal/2/14--5~6-2.png',
      },
      {
        id: 1478,
        name: 'Yellow spider',
        desc: 'Ultra-maneuverable combat machine that can quickly approach the enemy and cause confusion for the enemy, but the damage is very low',
        thumb1: '/assets/modal/2/14--7~8-1.png',
        thumb2: '/assets/modal/2/14--7~8-2.png',
      },
      {
        id: 15,
        name: 'Punisher',
        desc: 'With high-precision technology weapons, precise guidance, let the enemy lose their lives in the missile',
        thumb1: '/assets/modal/2/15-1.png',
        thumb2: '/assets/modal/2/15-2.png',
      },
      {
        id: 16,
        name: 'Double-headed flame',
        desc: 'It can spray ultra-high temperature flames, and the output of blue flame and red flame is mixed, which is like a pleasant symphony.',
        thumb1: '/assets/modal/2/16-1.png',
        thumb2: '/assets/modal/2/16-2.png',
      },
      {
        id: 17,
        name: 'Alpha',
        desc: 'The most mysterious fighting unit of the human race, no enemy can survive under his feet.',
        thumb1: '/assets/modal/2/17-1.png',
        thumb2: '/assets/modal/2/17-2.png',
      },
      {
        id: 18,
        name: 'Humpback whale',
        desc: 'The Terran aircraft carrier can resist small-scale attacks and is a battle command ship.',
        thumb1: '/assets/modal/2/18-1.png',
        thumb2: '/assets/modal/2/18-2.png',
      },
      {
        id: 19,
        name: 'Cheetah',
        desc: "Aviation first strike fighters, which can quickly approach the enemy's sky for harassment strikes",
        thumb1: '/assets/modal/2/19-1.png',
        thumb2: '/assets/modal/2/19-2.png',
      },
      {
        id: 20,
        name: 'Nightmare',
        desc: 'Enemy air nightmare, can quickly flash to the enemy position to attack, but the defense is very low',
        thumb1: '/assets/modal/2/20-1.png',
        thumb2: '/assets/modal/2/20-2.png',
      },
      {
        id: 21,
        name: 'Crow',
        desc: 'High-mobility fighters in the air have flexible attack methods, and high-tech weapons are their only means of defeating air to ground.',
        thumb1: '/assets/modal/2/21-1.png',
        thumb2: '/assets/modal/2/21-2.png',
      },
      {
        id: 22,
        name: 'Shark',
        desc: 'The escort of human command ships to ensure the survival of the mothership.',
        thumb1: '/assets/modal/2/22-1.png',
        thumb2: '/assets/modal/2/22-2.png',
      },
      {
        id: 23,
        name: 'Zealot MK1',
        desc: 'Infrared semi-automatic mecha warriors are the best choice for advancing troops',
        thumb1: '/assets/modal/2/23-1.png',
        thumb2: '/assets/modal/2/23-2.png',
      },
      {
        id: 24,
        name: 'Zealot MK2',
        desc: 'Infrared semi-automatic mecha warriors are the best choice for advancing troops',
        thumb1: '/assets/modal/2/24-1.png',
        thumb2: '/assets/modal/2/24-2.png',
      },
      {
        id: 25,
        name: 'Zealot MK3',
        desc: 'Infrared semi-automatic mecha warriors are the best choice for advancing troops',
        thumb1: '/assets/modal/2/25-1.png',
        thumb2: '/assets/modal/2/25-2.png',
      },
      {
        id: 26,
        name: 'Explorer',
        desc: 'Ground reconnaissance unit, without any attack capability',
        thumb1: '/assets/modal/2/26-1.png',
        thumb2: '/assets/modal/2/26-2.png',
      },
      {
        id: 27,
        name: 'Victor',
        desc: 'The Aurora Cannon has a very large single-unit killing ability, but the disadvantage is that the attack interval is long',
        thumb1: '/assets/modal/2/27-1.png',
        thumb2: '/assets/modal/2/27-2.png',
      },
      {
        id: 28,
        name: 'War machine',
        desc: 'The oldest troop vanguard of the human race can clear the front lines of the battlefield and open up the route of attack. Although it is an old machine, it is well-trained.',
        thumb1: '/assets/modal/2/28-1.png',
        thumb2: '/assets/modal/2/28-2.png',
      },
      {
        id: 29,
        name: 'Ranger',
        desc: 'Can detect terrain and create better attack routes, the only way to attack is to fit guided grenades',
        thumb1: '/assets/modal/2/29-1.png',
        thumb2: '/assets/modal/2/29-2.png',
      },
      {
        id: 30,
        name: 'Tango wolf',
        desc: 'It can carry out continuous strafing of a single unit, with strong continuous damage and inexhaustible energy.',
        thumb1: '/assets/modal/2/30-1.png',
        thumb2: '/assets/modal/2/30-2.png',
      },
    ],
    desc: 'Interstellar guards composed of the United Legion, wandering in various galaxies. Absolute mechanical capabilities and high-tech technology provide absolute combat protection, and have long-range tactical capabilities, which have a resistance to the Zerg. Production efficiency and building HP are relatively low due to wandering.',
    features: 'Defensive, Medical, Remote',
  },
  [RaceType.ZERG]: {
    name: 'race-3',
    children: [
      {
        id: 1,
        name: 'Crab bug',
        desc: 'It has a hard shell, which can quickly shuttle through the battlefield, the damage is not enough but the attack speed is very fast',
        thumb1: '/assets/modal/3/1-1.png',
        thumb2: '/assets/modal/3/1-2.png',
      },
      {
        id: 2,
        name: 'Multi-eyed beast',
        desc: 'Used for multiple eyes and tentacles, it can quickly distinguish the direction of the enemy and conduct sneak attacks',
        thumb1: '/assets/modal/3/2-1.png',
        thumb2: '/assets/modal/3/2-2.png',
      },
      {
        id: 3,
        name: 'Explosive Molten Worm',
        desc: 'The body is covered with explosive pulp, and as long as the enemy is identified, it will self-detonate, causing huge damage and continuous damage',
        thumb1: '/assets/modal/3/3-1.png',
        thumb2: '/assets/modal/3/3-2.png',
      },
      {
        id: 4,
        name: 'Ground cattle',
        desc: "Gundam's body and sponge skin can do local damage, attack method: eat the enemy in one bite!",
        thumb1: '/assets/modal/3/4-1.png',
        thumb2: '/assets/modal/3/4-2.png',
      },
      {
        id: 5,
        name: 'Armored Beetle',
        desc: 'Can curl into a ball close to the ground, dealing impact damage, and its long fangs can pierce enemies',
        thumb1: '/assets/modal/3/5-1.png',
        thumb2: '/assets/modal/3/5-2.png',
      },
      {
        id: 6,
        name: 'Ant spider',
        desc: 'The combination of ants and spiders can silently approach the enemy and apply deadly venom to the place',
        thumb1: '/assets/modal/3/6-1.png',
        thumb2: '/assets/modal/3/6-2.png',
      },
      {
        id: 7,
        name: 'Wing-toothed fish',
        desc: 'A fish variant that can fly at low altitudes, has an amazing bite force, and can release deadly poisonous gas from its tail',
        thumb1: '/assets/modal/3/7-1.png',
        thumb2: '/assets/modal/3/7-2.png',
      },
      {
        id: 8,
        name: 'Gragon foot ore mother',
        desc: 'A crawling troll with multiple dragon feet, covered with ore, and the suckers of the arms can hold the place firmly until death',
        thumb1: '/assets/modal/3/8-1.png',
        thumb2: '/assets/modal/3/8-2.png',
      },
      {
        id: 9,
        name: 'Abyssal Mouth',
        desc: 'A giant mouth in the shape of a piranha that opens to swallow larger units',
        thumb1: '/assets/modal/3/9-1.png',
        thumb2: '/assets/modal/3/9-2.png',
      },
      {
        id: 10,
        name: 'Giant pincer beetle',
        desc: 'Two super-heavy pliers, which can give the enemy a fatal blow, and even faint if not dead',
        thumb1: '/assets/modal/3/10-1.png',
        thumb2: '/assets/modal/3/10-2.png',
      },
      {
        id: 11,
        name: 'Spiked squid',
        desc: 'The spiky tentacles can put the enemy in the mouth and enjoy the taste of victory',
        thumb1: '/assets/modal/3/11-1.png',
        thumb2: '/assets/modal/3/11-2.png',
      },
      {
        id: 12,
        name: 'Nydus Worm',
        desc: 'Suddenly sprang from the tunnel, caught the local by surprise, disturbed the local position',
        thumb1: '/assets/modal/3/12-1.png',
        thumb2: '/assets/modal/3/12-2.png',
      },
      {
        id: 13,
        name: 'Giant Ant Lord',
        desc: "Mutated species from the void, the enemy's nightmare",
        thumb1: '/assets/modal/3/13-1.png',
        thumb2: '/assets/modal/3/13-2.png',
      },
      {
        id: 14,
        name: 'Bison',
        desc: 'The name has nothing to do with the figure, the crown on the single head has an incomparably rigid strength, which can repel the enemy',
        thumb1: '/assets/modal/3/14-1.png',
        thumb2: '/assets/modal/3/14-2.png',
      },
      {
        id: 15,
        name: 'Mammoth spider',
        desc: "Zerg giant display, with a sharp blade, can pierce the enemy's thick armor, and its own defense is also the top Zerg.",
        thumb1: '/assets/modal/3/15-1.png',
        thumb2: '/assets/modal/3/15-2.png',
      },
      {
        id: 16,
        name: 'Flying insects',
        desc: 'Aerial self-destruction soldier, which can harass the enemy in the air and cause continuous damage',
        thumb1: '/assets/modal/3/16-1.png',
        thumb2: '/assets/modal/3/16-2.png',
      },
      {
        id: 17,
        name: 'Stalker',
        desc: 'Can sneak underground to local rear camps and cause objective damage to the enemy',
        thumb1: '/assets/modal/3/17-1.png',
        thumb2: '/assets/modal/3/17-2.png',
      },
      {
        id: 18,
        name: 'Fearless Warrior',
        desc: 'Heroic and invincible Zerg display, cutting local queues with sharp dual ninjas',
        thumb1: '/assets/modal/3/18-1.png',
        thumb2: '/assets/modal/3/18-2.png',
      },
      {
        id: 19,
        name: 'One-eyed king',
        desc: 'Air scout',
        thumb1: '/assets/modal/3/19-1.png',
        thumb2: '/assets/modal/3/19-2.png',
      },
      {
        id: 20,
        name: 'Sandworm',
        desc: 'Ground scout, with a slowing effect',
        thumb1: '/assets/modal/3/20-1.png',
        thumb2: '/assets/modal/3/20-2.png',
      },
      {
        id: 21,
        name: 'Alien',
        desc: 'The hard shell on the back can withstand a variety of attacks, allowing it to quickly dash into place for harvesting',
        thumb1: '/assets/modal/3/21-1.png',
        thumb2: '/assets/modal/3/21-2.png',
      },
      {
        id: 22,
        name: 'Carrier',
        desc: 'An evolved version of the self-exploding monster, with six feet that can get closer to the place faster and explode, causing tons of damage',
        thumb1: '/assets/modal/3/22-1.png',
        thumb2: '/assets/modal/3/22-2.png',
      },
      {
        id: 23,
        name: 'Black water',
        desc: "A fast-attacking unit on the ground, with this agility and sustained damage species, group damage is the enemy's nightmare",
        thumb1: '/assets/modal/3/23-1.png',
        thumb2: '/assets/modal/3/23-2.png',
      },
      {
        id: 24,
        name: 'Quantum spider',
        desc: 'All made of quantum energy that can fire deadly quantum venom',
        thumb1: '/assets/modal/3/24-1.png',
        thumb2: '/assets/modal/3/24-2.png',
      },
      {
        id: 25,
        name: 'Voldemort Mantis',
        desc: 'A Zerg combat unit with strong jumping ability, which can leap into front of the enemy for powerful attacks',
        thumb1: '/assets/modal/3/25-1.png',
        thumb2: '/assets/modal/3/25-2.png',
      },
      {
        id: 26,
        name: 'Rogue beast',
        desc: 'With mutant cells, it can rampage in battle, and will never stop attacking until the end of life',
        thumb1: '/assets/modal/3/26-1.png',
        thumb2: '/assets/modal/3/26-2.png',
      },
      {
        id: 27,
        name: 'Corpse Shark',
        desc: "Zerg's meat warriors can launch first attacks to withstand all damage, but slow actions cannot play an offensive role",
        thumb1: '/assets/modal/3/27-1.png',
        thumb2: '/assets/modal/3/27-2.png',
      },
      {
        id: 28,
        name: 'Crabworm II',
        desc: 'It has a hard shell, which can quickly shuttle through the battlefield, the damage is not enough but the attack speed is very fast',
        thumb1: '/assets/modal/3/28-1.png',
        thumb2: '/assets/modal/3/28-2.png',
      },
      {
        id: 29,
        name: 'Crabworm III',
        desc: 'It has a hard shell, which can quickly shuttle through the battlefield, the damage is not enough but the attack speed is very fast',
        thumb1: '/assets/modal/3/29-1.png',
        thumb2: '/assets/modal/3/29-2.png',
      },
      {
        id: 30,
        name: 'Horned monkey',
        desc: 'Extremely hard horns that can stun enemies when approaching',
        thumb1: '/assets/modal/3/30-1.png',
        thumb2: '/assets/modal/3/30-2.png',
      },
    ],
    desc: 'A brutal race evolved from interstellar creatures, with extremely high damage, natural weapons and armor are comparable to other races, and their dedication makes the Zerg extremely strong and deadly. But no AOE and close range attack are their weak points.',
    features: 'Speed,High burst',
  },
};
