export declare type Breakpoints = string[];
export declare type MediaQueries = {
    xxs: string;
    xs: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
    xxl: string;
    nav: string;
};
export declare type MediaQueriesSize = {
    margin: string;
    marginr: string;
    padding: string;
};
export declare type BreakpointMap = {
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    nav: number;
};
export declare type Spacing = number[];
export declare type Radii = {
    small: string;
    default: string;
    card: string;
    nftImage: string;
    circle: string;
};
export declare type Shadows = {
    level1: string;
    active: string;
    success: string;
    warning: string;
    focus: string;
    inset: string;
    box: string;
    nav: string;
};
export declare type Gradients = {
    bubblegum: string;
    inverseBubblegum: string;
    cardHeader: string;
    blue: string;
    violet: string;
    violetAlt: string;
    gold: string;
};
export declare type Colors = {
    smHeadText: string;
    smTitletext: string;
    white_blue: string;
    white: string;
    primary: string;
    primaryBright: string;
    primaryDark: string;
    secondary: string;
    tertiary: string;
    success: string;
    failure: string;
    warning: string;
    cardBorder: string;
    contrast: string;
    dropdown: string;
    dropdownDeep: string;
    invertedContrast: string;
    input: string;
    inputPanel: string;
    inpuShadows: string;
    inputSecondary: string;
    inputSelect: string;
    background: string;
    backgroundPage: string;
    backgroundLight: string;
    backgroundSelect: string;
    backgroundDisabled: string;
    backgroundPrimary: string;
    backgroundMember: string;
    backgroundCard: string;
    textValue: string;
    backgroundAlt: string;
    text: string;
    white_black: string;
    member_num: string;
    textPrimary: string;
    textDisabled: string;
    textSubtle: string;
    disabled: string;
    gradients: Gradients;
    binance: string;
    overlay: string;
    gold: string;
    silver: string;
    bronze: string;
    triangleDinosaur: string;
    meat: string;
};
export declare type Filters = {
    brightness: string;
    grayscale: string;
    blur: string;
};
export declare type ZIndices = {
    dropdown: number;
    modal: number;
};
