export declare const LS_KEY = "storage_language";
export declare const fetchLocale: (locale: any) => Promise<{
    dataFormat: string;
    airTime: string;
    Exchange: string;
    "Connect Wallet": string;
    "Your %asset% Balance": string;
    "My %asset%": string;
    "Total %asset% Supply": string;
    Locked: string;
    "Total Liquidity": string;
    "View on BscScan": string;
    Finished: string;
    "Project site": string;
    "Project Site": string;
    "See Token Info": string;
    Total: string;
    End: string;
    "View Project Site": string;
    "Create a pool for your token": string;
    Close: string;
    Max: string;
    "%num% %symbol% Available": string;
    Cancel: string;
    Confirm: string;
    Warning: string;
    "I understand": string;
    "Pending Confirmation": string;
    "Buy new tokens with a brand new token sale model.": string;
    "You get the tokens.": string;
    "Want to launch your own IFO?": string;
    "Apply to launch": string;
    Core: string;
    Available: string;
    "Sign out": string;
    Select: string;
    "Launch Time": string;
    "For Sale": string;
    "Done!": string;
    "Read more": string;
    Connect: string;
    "Loading\u2026": string;
    Details: string;
    "Wallet Disconnected": string;
    Trade: string;
    More: string;
    Liquidity: string;
    Token: string;
    Pairs: string;
    Accounts: string;
    Active: string;
    Inactive: string;
    Dual: string;
    Compound: string;
    "In Wallet": string;
    "Loading...": string;
    Search: string;
    History: string;
    Burned: string;
    "To burn": string;
    "Total Value Locked": string;
    "Your wallet": string;
    Logout: string;
    Confirmed: string;
    Show: string;
    Hide: string;
    "Stake LP tokens": string;
    Stake: string;
    "I understand that people can view my wallet if they know my username": string;
    "Please connect your wallet to continue": string;
    "Get %symbol%": string;
    Balance: string;
    "Oops, page not found.": string;
    "Back Home": string;
    Live: string;
    Start: string;
    Finish: string;
    "Connect wallet to view": string;
    "Your volume": string;
    "Since start": string;
    Enable: string;
    Enabled: string;
    Enabling: string;
    Expired: string;
    Calculating: string;
    "Your history": string;
    All: string;
    "%num%d": string;
    d: string;
    h: string;
    m: string;
    "Success!": string;
    Blocks: string;
    "Add to Metamask": string;
    "Insufficient %symbol% balance": string;
    Buy: string;
    "Locate Assets": string;
    "%symbol% required": string;
    "Your History": string;
    Filter: string;
    Volume: string;
    Tokens: string;
    Contact: string;
    Merch: string;
    New: string;
    "Output is estimated. You will receive at least %amount% %symbol% or the transaction will revert.": string;
    "Output is estimated. You will receive at least": string;
    "or the transaction will revert.": string;
    "Output is estimated. If the price changes by more than %slippage%% your transaction will revert.": string;
    "Supplying %amountA% %symbolA% and %amountB% %symbolB%": string;
    "Removing %amountA% %symbolA% and %amountB% %symbolB%": string;
    "Swapping %amountA% %symbolA% for %amountB% %symbolB%": string;
    "Add Liquidity": string;
    "Add liquidity to receive LP tokens": string;
    "Liquidity providers earn a 0.1% trading fee on all trades made for that token pair, proportional to their share of the liquidity pool.": string;
    "You are creating a pool": string;
    "You are the first liquidity provider.": string;
    "The ratio of tokens you add will set the price of this pool.": string;
    "Once you are happy with the rate click supply to review.": string;
    "Initial prices and pool share": string;
    "Prices and pool share": string;
    "Unsupported Asset": string;
    "Enabling %asset%": string;
    "Enable %asset%": string;
    "Share of Pool": string;
    "%assetA% per %assetB%": string;
    "%asset% Deposited": string;
    Rates: string;
    "Create Pool & Supply": string;
    "Confirm Supply": string;
    "Confirm Swap": string;
    "Connect to a wallet to view your liquidity.": string;
    "Connect to a wallet to find pools": string;
    "Select a token to find your liquidity.": string;
    "No liquidity found.": string;
    "Don't see a pool you joined?": string;
    "Find other LP tokens": string;
    "Import Pool": string;
    "Import an existing pool": string;
    "Select a Token": string;
    "Pool Found!": string;
    "No pool found.": string;
    "Create pool.": string;
    "Manage this pool.": string;
    "Invalid pair.": string;
    "You don\u2019t have liquidity in this pool yet.": string;
    "%assetA%/%assetB% Burned": string;
    Price: string;
    Prices: string;
    "Remove %assetA%-%assetB% liquidity": string;
    Amount: string;
    Simple: string;
    Detailed: string;
    "Receive WBNB": string;
    "Receive BNB": string;
    Remove: string;
    Input: string;
    Output: string;
    "Trade tokens in an instant": string;
    "From (estimated)": string;
    From: string;
    "To (estimated)": string;
    To: string;
    "+ Add a send (optional)": string;
    "- Remove send": string;
    "Slippage Tolerance": string;
    "Insufficient liquidity for this trade.": string;
    "Try enabling multi-hop trades.": string;
    "Price Impact High": string;
    Swap: string;
    "Swap Anyway": string;
    "Recent Transactions": string;
    "clear all": string;
    "Clear all": string;
    "No recent transactions": string;
    "Are you sure?": string;
    "Expert mode turns off the 'Confirm' transaction prompt, and allows high slippage trades that often result in bad rates and lost funds.": string;
    "Only use this mode if you know what you\u2019re doing.": string;
    "Turn On Expert Mode": string;
    "Transaction Settings": string;
    "Interface Settings": string;
    "Toggle Expert Mode": string;
    "Bypasses confirmation modals and allows high slippage trades. Use at your own risk.": string;
    "Disable Multihops": string;
    "Restricts swaps to direct pairs only.": string;
    Audio: string;
    "\uD83D\uDC30 Turn down your volume a bit before you swap": string;
    "Your transaction will revert if the price changes unfavorably by more than this percentage.": string;
    "Enter a valid slippage percentage": string;
    "Your transaction may fail": string;
    "Your transaction may be frontrun": string;
    "Your transaction will revert if it is pending for more than this long.": string;
    minutes: string;
    "Token Amount": string;
    "Balance: %amount%": string;
    "LP tokens in your wallet": string;
    "Pooled %asset%": string;
    "By adding liquidity, you will earn 0.1% of all transactions for the pair, proportional to your share in the pool. The fees accrued each day will be added to the pool the following day, and you can receive your earnings by removing your liquidity.": string;
    "Common bases": string;
    "These tokens are commonly paired with other tokens.": string;
    "Expanded results from inactive Token Lists": string;
    "Tokens from inactive lists. Import specific tokens below or click 'Manage' to activate more lists.": string;
    "No results found.": string;
    Manage: string;
    "Manage Tokens": string;
    "Import Tokens": string;
    "Import List": string;
    "Import at your own risk": string;
    "By adding this list you are implicitly trusting that the data is correct. Anyone can create a list, including creating fake versions of existing lists and lists that claim to represent projects that do not have one.": string;
    "If you purchase a token from this list, you may not be able to sell it back.": string;
    Import: string;
    via: string;
    "Anyone can create a BEP20 token on BSC with any name, including creating fake versions of existing tokens and tokens that claim to represent projects that do not have a token.": string;
    "If you purchase an arbitrary token, you may be unable to sell it back.": string;
    "Unknown Source": string;
    Lists: string;
    See: string;
    "Update list": string;
    "https:// or ipfs:// or ENS name": string;
    Loaded: string;
    Loading: string;
    "Enter valid token address": string;
    "Custom Token": string;
    "Custom Tokens": string;
    "Unknown Error": string;
    "Select ": string;
    "Search name or paste address": string;
    "Add %asset% to Metamask": string;
    "Added %asset%": string;
    "Transaction Submitted": string;
    "Wallet Address or ENS name": string;
    Recipient: string;
    "Waiting For Confirmation": string;
    "Confirm this transaction in your wallet": string;
    Dismiss: string;
    Latest: string;
    "Notice for trading %symbol%": string;
    "To trade SAFEMOON, you must:": string;
    "Click on the settings icon": string;
    "Set your slippage tolerance to 12%+": string;
    "This is because SafeMoon taxes a 10% fee on each transaction:": string;
    "5% fee = redistributed to all existing holders": string;
    "5% fee = used to add liquidity": string;
    "Warning: BONDLY has been compromised. Please remove liqudity until further notice.": string;
    Claimed: string;
    Settings: string;
    "Transaction deadline": string;
    "Convert ERC-20 to BEP-20": string;
    "Need help ?": string;
    "Select a token": string;
    "Enter a recipient": string;
    "Invalid recipient": string;
    Supply: string;
    "Your Liquidity": string;
    "Remove liquidity to receive tokens back": string;
    "Trade anything. No registration, no hassle.": string;
    "Trade any token on Binance Smart Chain in seconds, just by connecting your wallet.": string;
    Learn: string;
    "BNB token": string;
    "BTC token": string;
    "Earn passive income with crypto.": string;
    "Unwrap %amoun% %symbolA% to %symbolB%": string;
    "Wrap %amoun% %symbolA% to %symbolB%": string;
    Wrap: string;
    Unwrap: string;
    "Aggregate trading": string;
    "Unable to get trading pool rewards using Aggregate trading": string;
    "Disable Route": string;
    "Minimum received": string;
    "Price Impact": string;
    "Liquidity Provider Fee": string;
    Fee: string;
    Route: string;
    "Your transaction will revert if there is a large, unfavorable price movement before it is confirmed.": string;
    "The difference between the market price and estimated price due to trade size.": string;
    "for each trade a 0.3% fee is paid": string;
    "0.1% to the LP token holders": string;
    "0.04% to the %symbol% stakers": string;
    "0.05% buyback %symbol% and burn": string;
    "0.025% buyback %symbol%, then to %symbol% LP": string;
    "0.025% to %symbol% holder": string;
    "0.06% to operation fund": string;
    "Routing through these tokens resulted in the best price for your trade.": string;
    "Money-hungry Dino": string;
    "Enter an amount": string;
    "Transaction rejected.": string;
    "Enter valid list location": string;
    "Error importing list": string;
    titleSetting: string;
    titleHistory: string;
    titleExchange: string;
    translationLast: string;
    translationEnd: string;
} | {
    dataFormat: string;
    airTime: string;
    Exchange: string;
    "Connect Wallet": string;
    "Your %asset% Balance": string;
    "My %asset%": string;
    "Total %asset% Supply": string;
    Locked: string;
    "Total Liquidity": string;
    "View on BscScan": string;
    Finished: string;
    "Project site": string;
    "Project Site": string;
    "See Token Info": string;
    Total: string;
    End: string;
    "View Project Site": string;
    "Create a pool for your token": string;
    Close: string;
    Max: string;
    "%num% %symbol% Available": string;
    Cancel: string;
    Confirm: string;
    Warning: string;
    "I understand": string;
    "Pending Confirmation": string;
    "Buy new tokens with a brand new token sale model.": string;
    "You get the tokens.": string;
    "Want to launch your own IFO?": string;
    "Apply to launch": string;
    Core: string;
    Available: string;
    "Sign out": string;
    Select: string;
    "Launch Time": string;
    "For Sale": string;
    "Done!": string;
    "Read more": string;
    Connect: string;
    "Loading\u2026": string;
    Details: string;
    "Wallet Disconnected": string;
    Trade: string;
    More: string;
    Liquidity: string;
    Token: string;
    Pairs: string;
    Accounts: string;
    Active: string;
    Inactive: string;
    Dual: string;
    Compound: string;
    "In Wallet": string;
    "Loading...": string;
    Search: string;
    History: string;
    Burned: string;
    "To burn": string;
    "Total Value Locked": string;
    "Your wallet": string;
    Logout: string;
    Confirmed: string;
    Show: string;
    Hide: string;
    "Stake LP tokens": string;
    Stake: string;
    "I understand that people can view my wallet if they know my username": string;
    "Please connect your wallet to continue": string;
    "Get %symbol%": string;
    Balance: string;
    "Oops, page not found.": string;
    "Back Home": string;
    Live: string;
    Start: string;
    Finish: string;
    "Connect wallet to view": string;
    "Your volume": string;
    "Since start": string;
    Enable: string;
    Enabled: string;
    Enabling: string;
    Expired: string;
    Calculating: string;
    "Your history": string;
    All: string;
    "%num%d": string;
    d: string;
    h: string;
    m: string;
    "Success!": string;
    Blocks: string;
    "Add to Metamask": string;
    "Insufficient %symbol% balance": string;
    Buy: string;
    "Locate Assets": string;
    "%symbol% required": string;
    "Your History": string;
    Filter: string;
    Volume: string;
    Tokens: string;
    Contact: string;
    Merch: string;
    New: string;
    "Output is estimated. If the price changes by more than %slippage%% your transaction will revert.": string;
    "Output is estimated. You will receive at least  %amount% %symbol% or the transaction will revert.": string;
    "Output is estimated. You will receive at least": string;
    "or the transaction will revert.": string;
    "Supplying %amountA% %symbolA% and %amountB% %symbolB%": string;
    "Removing %amountA% %symbolA% and %amountB% %symbolB%": string;
    "Swapping %amountA% %symbolA% for %amountB% %symbolB%": string;
    "Add Liquidity": string;
    "Add liquidity to receive LP tokens": string;
    "Liquidity providers earn a 0.1% trading fee on all trades made for that token pair, proportional to their share of the liquidity pool.": string;
    "You are creating a pool": string;
    "You are the first liquidity provider.": string;
    "The ratio of tokens you add will set the price of this pool.": string;
    "Once you are happy with the rate click supply to review.": string;
    "Initial prices and pool share": string;
    "Prices and pool share": string;
    "Unsupported Asset": string;
    "Enabling %asset%": string;
    "Enable %asset%": string;
    "Share of Pool": string;
    "%assetA% per %assetB%": string;
    "%asset% Deposited": string;
    Rates: string;
    "Create Pool & Supply": string;
    "Confirm Supply": string;
    "Confirm Swap": string;
    "Connect to a wallet to view your liquidity.": string;
    "Connect to a wallet to find pools": string;
    "Select a token to find your liquidity.": string;
    "No liquidity found.": string;
    "Don't see a pool you joined?": string;
    "Find other LP tokens": string;
    "Import Pool": string;
    "Import an existing pool": string;
    "Select a Token": string;
    "Pool Found!": string;
    "No pool found.": string;
    "Create pool.": string;
    "Manage this pool.": string;
    "Invalid pair.": string;
    "You don\u2019t have liquidity in this pool yet.": string;
    "%assetA%/%assetB% Burned": string;
    Price: string;
    Prices: string;
    "Remove %assetA%-%assetB% liquidity": string;
    Amount: string;
    Simple: string;
    Detailed: string;
    "Receive WBNB": string;
    "Receive BNB": string;
    Remove: string;
    Input: string;
    Output: string;
    "Trade tokens in an instant": string;
    "From (estimated)": string;
    From: string;
    "To (estimated)": string;
    To: string;
    "+ Add a send (optional)": string;
    "- Remove send": string;
    "Slippage Tolerance": string;
    "Insufficient liquidity for this trade.": string;
    "Try enabling multi-hop trades.": string;
    "Price Impact High": string;
    Swap: string;
    "Swap Anyway": string;
    "Recent Transactions": string;
    "clear all": string;
    "Clear all": string;
    "No recent transactions": string;
    "Are you sure?": string;
    "Expert mode turns off the 'Confirm' transaction prompt, and allows high slippage trades that often result in bad rates and lost funds.": string;
    "Only use this mode if you know what you\u2019re doing.": string;
    "Turn On Expert Mode": string;
    "Transaction Settings": string;
    "Interface Settings": string;
    "Toggle Expert Mode": string;
    "Bypasses confirmation modals and allows high slippage trades. Use at your own risk.": string;
    "Disable Multihops": string;
    "Restricts swaps to direct pairs only.": string;
    Audio: string;
    "\uD83D\uDC30 Turn down your volume a bit before you swap": string;
    "Your transaction will revert if the price changes unfavorably by more than this percentage.": string;
    "Enter a valid slippage percentage": string;
    "Your transaction may fail": string;
    "Your transaction may be frontrun": string;
    "Your transaction will revert if it is pending for more than this long.": string;
    minutes: string;
    "Token Amount": string;
    "Balance: %amount%": string;
    "LP tokens in your wallet": string;
    "Pooled %asset%": string;
    "By adding liquidity, you will earn 0.1% of all transactions for the pair, proportional to your share in the pool. The fees accrued each day will be added to the pool the following day, and you can receive your earnings by removing your liquidity.": string;
    "Common bases": string;
    "These tokens are commonly paired with other tokens.": string;
    "Expanded results from inactive Token Lists": string;
    "Tokens from inactive lists. Import specific tokens below or click 'Manage' to activate more lists.": string;
    "No results found.": string;
    Manage: string;
    "Manage Tokens": string;
    "Import Tokens": string;
    "Import List": string;
    "Import at your own risk": string;
    "By adding this list you are implicitly trusting that the data is correct. Anyone can create a list, including creating fake versions of existing lists and lists that claim to represent projects that do not have one.": string;
    "If you purchase a token from this list, you may not be able to sell it back.": string;
    Import: string;
    via: string;
    "Anyone can create a BEP20 token on BSC with any name, including creating fake versions of existing tokens and tokens that claim to represent projects that do not have a token.": string;
    "If you purchase an arbitrary token, you may be unable to sell it back.": string;
    "Unknown Source": string;
    Lists: string;
    See: string;
    "Update list": string;
    "https:// or ipfs:// or ENS name": string;
    Loaded: string;
    Loading: string;
    "Enter valid token address": string;
    "Custom Token": string;
    "Custom Tokens": string;
    "Unknown Error": string;
    "Select ": string;
    "Search name or paste address": string;
    "Add %asset% to Metamask": string;
    "Added %asset%": string;
    "Transaction Submitted": string;
    "Wallet Address or ENS name": string;
    Recipient: string;
    "Waiting For Confirmation": string;
    "Confirm this transaction in your wallet": string;
    Dismiss: string;
    Latest: string;
    "Notice for trading %symbol%": string;
    "To trade SAFEMOON, you must:": string;
    "Click on the settings icon": string;
    "Set your slippage tolerance to 12%+": string;
    "This is because SafeMoon taxes a 10% fee on each transaction:": string;
    "5% fee = redistributed to all existing holders": string;
    "5% fee = used to add liquidity": string;
    "Warning: BONDLY has been compromised. Please remove liqudity until further notice.": string;
    Claimed: string;
    Settings: string;
    "Transaction deadline": string;
    "Convert ERC-20 to BEP-20": string;
    "Need help ?": string;
    "Select a token": string;
    "Enter a recipient": string;
    "Invalid recipient": string;
    Supply: string;
    Accept: string;
    "Price Updated": string;
    "Your Liquidity": string;
    "Remove liquidity to receive tokens back": string;
    "Trade anything. No registration, no hassle.": string;
    "Trade any token on Binance Smart Chain in seconds, just by connecting your wallet.": string;
    Learn: string;
    "BNB token": string;
    "BTC token": string;
    "Earn passive income with crypto.": string;
    "Unwrap %amoun% %symbolA% to %symbolB%": string;
    "Wrap %amoun% %symbolA% to %symbolB%": string;
    Wrap: string;
    Unwrap: string;
    "Aggregate trading": string;
    "Unable to get trading pool rewards using Aggregate trading": string;
    "Disable Route": string;
    "Minimum received": string;
    "Maximum sold": string;
    "Your transaction will revert if there is a large, unfavorable price movement before it is confirmed.": string;
    "Price Impact": string;
    Route: string;
    "The difference between the market price and your price due to trade size.": string;
    "The difference between the market price and estimated price due to trade size.": string;
    "for each trade a 0.3% fee is paid": string;
    "0.1% to the LP token holders": string;
    "0.04% to the %symbol% stakers": string;
    "0.05% buyback %symbol% and burn": string;
    "0.025% buyback %symbol%, then to %symbol% LP": string;
    "0.025% to %symbol% holder": string;
    "0.06% to operation fund": string;
    "Liquidity Provider Fee": string;
    Fee: string;
    "Routing through these tokens resulted in the best price for your trade.": string;
    "Money-hungry Dino": string;
    "Enter an amount": string;
    "Transaction rejected.": string;
    "Enter valid list location": string;
    "Error importing list": string;
    titleSetting: string;
    titleHistory: string;
    titleExchange: string;
    translationLast: string;
    translationEnd: string;
} | {
    dataFormat: string;
    airTime: string;
    Exchange: string;
    "Connect Wallet": string;
    "Your %asset% Balance": string;
    "My %asset%": string;
    "Total %asset% Supply": string;
    Locked: string;
    "Total Liquidity": string;
    "View on BscScan": string;
    Finished: string;
    "Project site": string;
    "Project Site": string;
    "See Token Info": string;
    Total: string;
    End: string;
    "View Project Site": string;
    "Create a pool for your token": string;
    Close: string;
    Max: string;
    "%num% %symbol% Available": string;
    Cancel: string;
    Confirm: string;
    Warning: string;
    "I understand": string;
    "Pending Confirmation": string;
    "Buy new tokens with a brand new token sale model.": string;
    "You get the tokens.": string;
    "Want to launch your own IFO?": string;
    "Apply to launch": string;
    Core: string;
    Available: string;
    "Sign out": string;
    Select: string;
    "Launch Time": string;
    "For Sale": string;
    "Done!": string;
    "Read more": string;
    Connect: string;
    "Loading\u2026": string;
    Details: string;
    "Wallet Disconnected": string;
    Trade: string;
    More: string;
    Liquidity: string;
    Token: string;
    Pairs: string;
    Accounts: string;
    Active: string;
    Inactive: string;
    Dual: string;
    Compound: string;
    "In Wallet": string;
    "Loading...": string;
    Search: string;
    History: string;
    Burned: string;
    "To burn": string;
    "Total Value Locked": string;
    "Your wallet": string;
    Logout: string;
    Confirmed: string;
    Show: string;
    Hide: string;
    "Stake LP tokens": string;
    Stake: string;
    "I understand that people can view my wallet if they know my username": string;
    "Please connect your wallet to continue": string;
    "Get %symbol%": string;
    Balance: string;
    "Oops, page not found.": string;
    "Back Home": string;
    Live: string;
    Start: string;
    Finish: string;
    "Connect wallet to view": string;
    "Your volume": string;
    "Since start": string;
    Enable: string;
    Enabled: string;
    Enabling: string;
    Expired: string;
    Calculating: string;
    "Your history": string;
    All: string;
    "%num%d": string;
    d: string;
    h: string;
    m: string;
    "Success!": string;
    Blocks: string;
    "Add to Metamask": string;
    "Insufficient %symbol% balance": string;
    Buy: string;
    "Locate Assets": string;
    "%symbol% required": string;
    "Your History": string;
    Filter: string;
    Volume: string;
    Tokens: string;
    Contact: string;
    Merch: string;
    New: string;
    "Output is estimated. If the price changes by more than %slippage%% your transaction will revert.": string;
    "Output is estimated. You will receive at least  %amount% %symbol% or the transaction will revert.": string;
    "Output is estimated. You will receive at least": string;
    "or the transaction will revert.": string;
    "Supplying %amountA% %symbolA% and %amountB% %symbolB%": string;
    "Removing %amountA% %symbolA% and %amountB% %symbolB%": string;
    "Swapping %amountA% %symbolA% for %amountB% %symbolB%": string;
    "Add Liquidity": string;
    "Add liquidity to receive LP tokens": string;
    "Liquidity providers earn a 0.1% trading fee on all trades made for that token pair, proportional to their share of the liquidity pool.": string;
    "You are creating a pool": string;
    "You are the first liquidity provider.": string;
    "The ratio of tokens you add will set the price of this pool.": string;
    "Once you are happy with the rate click supply to review.": string;
    "Initial prices and pool share": string;
    "Prices and pool share": string;
    "Unsupported Asset": string;
    "Enabling %asset%": string;
    "Enable %asset%": string;
    "Share of Pool": string;
    "%assetA% per %assetB%": string;
    "%asset% Deposited": string;
    Rates: string;
    "Create Pool & Supply": string;
    "Confirm Supply": string;
    "Confirm Swap": string;
    "Connect to a wallet to view your liquidity.": string;
    "Connect to a wallet to find pools": string;
    "Select a token to find your liquidity.": string;
    "No liquidity found.": string;
    "Don't see a pool you joined?": string;
    "Find other LP tokens": string;
    "Import Pool": string;
    "Import an existing pool": string;
    "Select a Token": string;
    "Pool Found!": string;
    "No pool found.": string;
    "Create pool.": string;
    "Manage this pool.": string;
    "Invalid pair.": string;
    "You don\u300Ft have liquidity in this pool yet.": string;
    "%assetA%/%assetB% Burned": string;
    Price: string;
    Prices: string;
    "Remove %assetA%-%assetB% liquidity": string;
    Amount: string;
    Simple: string;
    Detailed: string;
    "Receive WBNB": string;
    "Receive BNB": string;
    Remove: string;
    Input: string;
    Output: string;
    "Trade tokens in an instant": string;
    "From (estimated)": string;
    From: string;
    "To (estimated)": string;
    To: string;
    "+ Add a send (optional)": string;
    "- Remove send": string;
    "Slippage Tolerance": string;
    "Insufficient liquidity for this trade.": string;
    "Try enabling multi-hop trades.": string;
    "Price Impact High": string;
    Swap: string;
    "Swap Anyway": string;
    "Recent Transactions": string;
    "clear all": string;
    "Clear all": string;
    "No recent transactions": string;
    "Are you sure?": string;
    "Expert mode turns off the 'Confirm' transaction prompt, and allows high slippage trades that often result in bad rates and lost funds.": string;
    "Only use this mode if you know what you\u300Fre doing.": string;
    "Turn On Expert Mode": string;
    "Transaction Settings": string;
    "Interface Settings": string;
    "Toggle Expert Mode": string;
    "Bypasses confirmation modals and allows high slippage trades. Use at your own risk.": string;
    "Disable Multihops": string;
    "Restricts swaps to direct pairs only.": string;
    Audio: string;
    "\uD83D\uDC30 Turn down your volume a bit before you swap": string;
    "Your transaction will revert if the price changes unfavorably by more than this percentage.": string;
    "Enter a valid slippage percentage": string;
    "Your transaction may fail": string;
    "Your transaction may be frontrun": string;
    "Your transaction will revert if it is pending for more than this long.": string;
    minutes: string;
    "Token Amount": string;
    "Balance: %amount%": string;
    "LP tokens in your wallet": string;
    "Pooled %asset%": string;
    "By adding liquidity, you will earn 0.1% of all transactions for the pair, proportional to your share in the pool. The fees accrued each day will be added to the pool the following day, and you can receive your earnings by removing your liquidity.": string;
    "Common bases": string;
    "These tokens are commonly paired with other tokens.": string;
    "Expanded results from inactive Token Lists": string;
    "Tokens from inactive lists. Import specific tokens below or click 'Manage' to activate more lists.": string;
    "No results found.": string;
    Manage: string;
    "Manage Tokens": string;
    "Import Tokens": string;
    "Import List": string;
    "Import at your own risk": string;
    "By adding this list you are implicitly trusting that the data is correct. Anyone can create a list, including creating fake versions of existing lists and lists that claim to represent projects that do not have one.": string;
    "If you purchase a token from this list, you may not be able to sell it back.": string;
    Import: string;
    via: string;
    "Anyone can create a BEP20 token on BSC with any name, including creating fake versions of existing tokens and tokens that claim to represent projects that do not have a token.": string;
    "If you purchase an arbitrary token, you may be unable to sell it back.": string;
    "Unknown Source": string;
    Lists: string;
    See: string;
    "Update list": string;
    "https:// or ipfs:// or ENS name": string;
    Loaded: string;
    Loading: string;
    "Enter valid token address": string;
    "Custom Token": string;
    "Custom Tokens": string;
    "Unknown Error": string;
    "Select ": string;
    "Search name or paste address": string;
    "Add %asset% to Metamask": string;
    "Added %asset%": string;
    "Transaction Submitted": string;
    "Wallet Address or ENS name": string;
    Recipient: string;
    "Waiting For Confirmation": string;
    "Confirm this transaction in your wallet": string;
    Dismiss: string;
    Latest: string;
    "Notice for trading %symbol%": string;
    "To trade SAFEMOON, you must:": string;
    "Click on the settings icon": string;
    "Set your slippage tolerance to 12%+": string;
    "This is because SafeMoon taxes a 10% fee on each transaction:": string;
    "5% fee = redistributed to all existing holders": string;
    "5% fee = used to add liquidity": string;
    "Warning: BONDLY has been compromised. Please remove liqudity until further notice.": string;
    Claimed: string;
    Settings: string;
    "Transaction deadline": string;
    "Convert ERC-20 to BEP-20": string;
    "Need help ?": string;
    "Select a token": string;
    "Enter a recipient": string;
    "Invalid recipient": string;
    Supply: string;
    Accept: string;
    "Price Updated": string;
    "Your Liquidity": string;
    "Remove liquidity to receive tokens back": string;
    "Trade anything. No registration, no hassle.": string;
    "Trade any token on Binance Smart Chain in seconds, just by connecting your wallet.": string;
    Learn: string;
    "BNB token": string;
    "BTC token": string;
    "Earn passive income with crypto.": string;
    "Unwrap %amoun% %symbolA% to %symbolB%": string;
    "Wrap %amoun% %symbolA% to %symbolB%": string;
    Wrap: string;
    Unwrap: string;
    "Aggregate trading": string;
    "Unable to get trading pool rewards using Aggregate trading": string;
    "Disable Route": string;
    "Minimum received": string;
    "Maximum sold": string;
    "Your transaction will revert if there is a large, unfavorable price movement before it is confirmed.": string;
    "Price Impact": string;
    Route: string;
    "The difference between the market price and your price due to trade size.": string;
    "The difference between the market price and estimated price due to trade size.": string;
    "for each trade a 0.3% fee is paid": string;
    "0.1% to the LP token holders": string;
    "0.04% to the %symbol% stakers": string;
    "0.05% buyback %symbol% and burn": string;
    "0.025% buyback %symbol%, then to %symbol% LP": string;
    "0.025% to %symbol% holder": string;
    "0.06% to operation fund": string;
    "Liquidity Provider Fee": string;
    Fee: string;
    "Routing through these tokens resulted in the best price for your trade.": string;
    "Money-hungry Dino": string;
    "Enter an amount": string;
    "Transaction rejected.": string;
    "Enter valid list location": string;
    "Error importing list": string;
    titleSetting: string;
    titleHistory: string;
    titleExchange: string;
    translationLast: string;
    translationEnd: string;
}>;
export declare const getLanguageCodeFromLS: () => string;
